import "./globals.css";
import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import { Inter } from "next/font/google";

import Navbar from "@/components/Navbar";
import ModalProvider from "@/components/modal/ModalProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <ModalProvider />
          <main className="relative mt-[8vh] flex flex-col">
            <div className="fixed top-0 z-50 h-[8vh] w-full bg-zinc-800">
              <Navbar />
            </div>
            {children}
          </main>
        </body>
      </html>
    </ClerkProvider>
  );
}
